- hosts: web
  become: true

  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Run nginx container
      community.docker.docker_container:
        name: nginx
        image: nginx
        state: started
        restart_policy: always
        ports:
          - "80:80"
